package app.admin;


/**
* app/admin/AdminHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, November 8, 2017 12:33:45 AM EST
*/

abstract public class AdminHelper
{
  private static String  _id = "IDL:app/admin/Admin:1.0";

  public static void insert (org.omg.CORBA.Any a, app.admin.Admin that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static app.admin.Admin extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (app.admin.AdminHelper.id (), "Admin");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static app.admin.Admin read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdminStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, app.admin.Admin value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static app.admin.Admin narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.admin.Admin)
      return (app.admin.Admin)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.admin._AdminStub stub = new app.admin._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static app.admin.Admin unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.admin.Admin)
      return (app.admin.Admin)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.admin._AdminStub stub = new app.admin._AdminStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
