package app.admin;


/**
* app/admin/AdminPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, November 8, 2017 12:33:45 AM EST
*/

public abstract class AdminPOA extends org.omg.PortableServer.Servant
 implements app.admin.AdminOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createRoom", new java.lang.Integer (0));
    _methods.put ("deleteRoom", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // app/admin/Admin/createRoom
       {
         String adminID = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String timeSlots[] = app.admin.AdminPackage.timeSlotSequenceHelper.read (in);
         String $result = null;
         $result = this.createRoom (adminID, roomNumber, date, timeSlots);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // app/admin/Admin/deleteRoom
       {
         String adminID = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String timeSlots[] = app.admin.AdminPackage.timeSlotSequenceHelper.read (in);
         String $result = null;
         $result = this.deleteRoom (adminID, roomNumber, date, timeSlots);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:app/admin/Admin:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Admin _this() 
  {
    return AdminHelper.narrow(
    super._this_object());
  }

  public Admin _this(org.omg.CORBA.ORB orb) 
  {
    return AdminHelper.narrow(
    super._this_object(orb));
  }


} // class AdminPOA
