package app.admin;

/**
* app/admin/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, November 28, 2017 11:34:48 PM EST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public app.admin.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (app.admin.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = app.admin.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    app.admin.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return app.admin.AdminHelper.type ();
  }

}
