package app.admin;


/**
* app/admin/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, November 8, 2017 12:33:45 AM EST
*/

public interface AdminOperations 
{
  String createRoom (String adminID, int roomNumber, String date, String[] timeSlots);
  String deleteRoom (String adminID, int roomNumber, String date, String[] timeSlots);
} // interface AdminOperations
