package app.admin;


/**
* app/admin/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, November 28, 2017 11:34:48 PM EST
*/

public interface Admin extends AdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Admin
