package app.admin;


/**
* app/admin/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, November 28, 2017 11:34:48 PM EST
*/

public interface AdminOperations 
{
  String createRoom (String adminID, int roomNumber, String date, String timeSlots);
  String deleteRoom (String adminID, int roomNumber, String date, String timeSlots);
} // interface AdminOperations
