package app.server;


/**
* app/server/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, November 28, 2017 11:34:48 PM EST
*/

public interface ServerOperations  extends app.admin.AdminOperations, app.student.StudentOperations
{
} // interface ServerOperations
