package app.server;


/**
* app/server/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, November 8, 2017 12:33:45 AM EST
*/

public interface ServerOperations  extends app.admin.AdminOperations, app.student.StudentOperations
{
} // interface ServerOperations
