package app.server;


/**
* app/server/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, December 6, 2017 6:38:31 o'clock PM EST
*/

public interface ServerOperations 
{

  //        typedef sequence<string> listSlots;
  String createRoom (String admin_id, int room_number, String date, String list_of_time_slots);
  String deleteRoom (String admin_id, int room_number, String date, String list_of_time_slots);
  String bookRoom (String student_id, String campus_name, int room_number, String date, String slots);
  String getAvailableTimeSlots (String student_id, String date);
  String cancelBooking (String student_id, String booking_id);
  String changeReservation (String student_id, String booking_id, String new_campus_name, int new_room_no, String new_date, String new_time_slot);
} // interface ServerOperations
