package app.student;


/**
* app/student/StudentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Wednesday, November 8, 2017 12:33:45 AM EST
*/

abstract public class StudentHelper
{
  private static String  _id = "IDL:app/student/Student:1.0";

  public static void insert (org.omg.CORBA.Any a, app.student.Student that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static app.student.Student extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (app.student.StudentHelper.id (), "Student");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static app.student.Student read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StudentStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, app.student.Student value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static app.student.Student narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.student.Student)
      return (app.student.Student)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.student._StudentStub stub = new app.student._StudentStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static app.student.Student unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof app.student.Student)
      return (app.student.Student)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      app.student._StudentStub stub = new app.student._StudentStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
