package app.student;


/**
* app/student/StudentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Tuesday, November 28, 2017 11:34:48 PM EST
*/

public interface StudentOperations 
{
  String bookRoom (String studentID, String campusName, int roomNumber, String date, String timeSlot);
  String getAvailableTimeSlots (String studentID, String date);
  String cancelBooking (String studentID, String bookingID);
  String changeReservation (String studentID, String bookingID, String campusName, int roomNumber, String date, String timesSlot);
} // interface StudentOperations
