module app {
    module admin {
        interface Admin {
            string createRoom(in string adminID, in long roomNumber, in string date, in string timeSlots);

            string deleteRoom(in string adminID, in long roomNumber, in string date, in string timeSlots);
        };
    };

    module student {
        interface Student {
            string bookRoom(in string studentID, in string campusName, in long roomNumber, in string date, in string timeSlot);

            string getAvailableTimeSlots(in string studentID, in string date);

            string cancelBooking(in string studentID, in string bookingID);

            string changeReservation(in string studentID, in string bookingID, in string campusName, in long roomNumber, in string date, in string timesSlot);
        };
    };

    module server {
        interface Server : app::admin::Admin, app::student::Student {
        };
    };
};