module app
{
    module server
    {
        interface Server
        {
    //        typedef sequence<string> listSlots;
            string createRoom(in string admin_id, in long room_number, in string date, in string list_of_time_slots);
            string deleteRoom(in string admin_id, in long room_number, in string date, in string list_of_time_slots);
            string bookRoom(in string student_id, in string campus_name, in long room_number, in string date, in string slots);
            string getAvailableTimeSlots(in string student_id,in string date);
            string cancelBooking(in string student_id, in string booking_id);
            string changeReservation (in string student_id, in string booking_id, in string new_campus_name, in long new_room_no, in string new_date, in string new_time_slot);
        };
    };
};
