package app.rm.replica.mudra;


/**
* App/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mudra-PC/eclipse-workspace/DssServer/src/ServerInterface.idl
* Tuesday, November 28, 2017 3:31:18 PM EST
*/

public interface ServerInterfaceOperations 
{

  /**
  		 * When a admin invokes this method through a client program called AdminClient, the server attempts 
  		 * to create a room with the information passed if the room does not exist.
  		 * 
  		 * @param adminID
  		 * @param roomNo
  		 * @param date
  		 * @param timeSlot
  		 * @return true if room was created in replica.
  		 */
  boolean createRoom(String adminID, int roomNo, String date, String timeSlot);

  /**
  		 * When a admin invokes this method through a client program called AdminClient, the server attempts 
  		 * to delete a room with the information passed if the room exist.
  		 * 
  		 * @param adminID
  		 * @param roomNo
  		 * @param date
  		 * @param timeSlot
  		 * @return true if room was deleted from replica.
  		 */
  boolean deleteRoom(String adminID, int roomNo, String date, String timeSlot);

  /**
  		 * When a student invokes this method through a client program called StudentClient, the server attempts 
  		 * to book a room with the information passed if the room exist.
  		 * 
  		 * @param studentID
  		 * @param campusName
  		 * @param roomNo
  		 * @param date
  		 * @param timeSlot
  		 * @return true if booking was made in replica.
  		 */
  boolean bookRoom(String studentID, String campusName, int roomNo, String date, String timeSlot);

  /**
  		 * When a student invokes this method through a client program called StudentClient, the server attempts 
  		 * to get and display all the timeSlots that are available with the information passed.
  		 * 
  		 * @param studentID
  		 * @param date
  		 * @return
  		 */
  boolean getTimeSlots(String studentID, String date);

  /**
  		 * When a student invokes this method through a client program called StudentClient, the server attempts 
  		 * to cancel a room booking with the information passed if the booking exist.
  		 * 
  		 * @param bookingID
  		 * @param studentID
  		 * @return true if booking was from replica.
  		 */
  boolean cancelRoom(String bookingID, String studentID);

  /**
  		 * When a student invokes this method through a client program called StudentClient, the server attempts 
  		 * to change room booking with the information passed if the booking exist.
  		 * 
  		 * @param studentID
  		 * @param bookingID
  		 * @param campusName
  		 * @param roomNo
  		 * @param date
  		 * @param timeSlot
  		 * @return true if booking was from replica.
  		 */
  boolean changeBooking(String studentID, String bookingID, String campusName, int roomNo, String date, String timeSlot);
} // interface ServerInterfaceOperations
